version: '3'

services:

  # MYSQL
  mysql:
    build:
      context: ./config/docker/mysql
      args:
        mysql_version: ${MYSQL_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}-mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    restart: always

  # PHPMYADMIN
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${COMPOSE_PROJECT_NAME}-phpmyadmin
    depends_on: 
      - mysql
    environment:  
      PMA_HOST: mysql
    ports: 
      - '${PHPMYADMIN_PORT}:80'
    restart: always

  # PHP
  php:
    build:
      context: ./config/docker/php
      args:
        php_version: ${PHP_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}-php
    ports:
      - "${PHP_PORT}:80"
    volumes:
      - ./:/var/www/html
    links:
      - mysql
